-- Create the Warehouse (The Compute Engine)
CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_WH 
WITH WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE;

-- Create the Database
CREATE DATABASE IF NOT EXISTS ECOMMERCE_DW;

-- Create the Bronze/Raw Schema
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DW.RAW_BRONZE;

-- Create the Tables to hold the API data
-- 1. Customers Table (Relational Source)
CREATE OR REPLACE TABLE STG_CUSTOMERS (
    CUSTOMER_ID STRING, 
    NAME STRING, 
    EMAIL STRING, 
    COUNTRY STRING, 
    CREATED_AT TIMESTAMP, 
    _LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Products Table (The Catalog)
CREATE OR REPLACE TABLE STG_PRODUCTS (
    ID STRING, 
    NAME STRING, 
    CATEGORY STRING, 
    COST FLOAT, 
    PRICE FLOAT, 
    _LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Orders Table (Header Data)
CREATE OR REPLACE TABLE STG_ORDERS (
    ORDER_ID STRING, 
    CUSTOMER_ID STRING, 
    ORDER_DATE TIMESTAMP, 
    TOTAL_AMOUNT FLOAT, 
    STATUS STRING, 
    _LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Order Items Table (Granular Details)
CREATE OR REPLACE TABLE STG_ORDER_ITEMS (
    ITEM_ID STRING, 
    ORDER_ID STRING, 
    PRODUCT_ID STRING, 
    QUANTITY INTEGER, 
    UNIT_PRICE FLOAT, 
    _LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
